package testgen.data.model;

import java.util.ArrayList;
import java.util.List;

public class Section {
	private List<Question> questions;
	private String name;

	public Section(String name) {
		this.name = name;
		this.questions = new ArrayList<>();
	}

	public void appendQuestion(Question question) {
		this.questions.add(question);
	}

	// autogenerated code
	public String getName() {
		return name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((questions == null) ? 0 : questions.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Section other = (Section) obj;
		if (questions == null) {
			if (other.questions != null)
				return false;
		} else if (!questions.equals(other.questions))
			return false;
		return true;
	}
}
