package testgen.data.model;

import java.util.ArrayList;
import java.util.List;

public class Test {
	private String name;

	private List<Section> sections;

	public Test(String testName) {
		this.name = testName;
		sections = new ArrayList<>();
	}

	public void appendSection(Section section) {
		this.sections.add(section);
	}

	// autogenerated code
	public String getName() {
		return name;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((sections == null) ? 0 : sections.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Test other = (Test) obj;
		if (sections == null) {
			if (other.sections != null)
				return false;
		} else if (!sections.equals(other.sections))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Test [name=").append(name).append(", sections=")
				.append(sections).append("]");
		return builder.toString();
	}
}